web_mvc/config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  get 'bienvenido/index'
  resources :articulos

   root 'bienvenido#index'

end

web_mvc/app/models/articulo.rb
class Articulo < ActiveRecord::Base
	belongs_to :usuario
	validates :titulo,presence:true
	validates :cuerpo,presence:true, length:{minimum: 20}
	before_save :set_numero_visitas 

	def update_numero_visitas
		self.save if self.numero_visitas.nil?
		self.update(numero_visitas: self.numero_visitas + 1)
	end	

	private 

	def set_numero_visitas
		self.numero_visitas ||= 0
	end
end

web_mvc/app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articulos       
end

web_mvc/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

web_mvc/app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
	
	before_action :authenticate_usuario!,except: [:show,:index]

	def index
		@articulo = Articulo.all
	end	

	def show
		@articulo = Articulo.find(params[:id])
		@articulo.update_numero_visitas
	end

	def new 
		 @articulo = Articulo.new
	end

	def create 
		@articulo = current_usuario.articulos.new(articulo_params)
		
		if @articulo.save
			redirect_to @articulo
		else
			render :new	
		end			
	end

	def destroy
		@articulo = Articulo.find(params[:id])
		@articulo.destroy
		redirect_to '/articulos'
	end

	def edit 
		@articulo = Articulo.find(params[:id])

	end 

	def update 
		@articulo = Articulo.find(params[:id])
		if @articulo.update(articulo_params)
			redirect_to "/articulos"
		else
			render :edit
		end		
	end	

	private 

	def articulo_params
		params.require(:articulo).permit(:titulo,:cuerpo)
	end	
end

web_mvc/app/controllers/bienvenido_controller.rb
class BienvenidoController < ApplicationController
  def index
  end
end

web_mvc/app/helpers/application_helper.rb
module ApplicationHelper
end

web_mvc/app/helpers/articulos_helper.rb
module ArticulosHelper
end

web_mvc/app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

web_mvc/app/views/bienvenido/index.html.erb
<h1>Bienvenido al blog de prubea de Diego para ruby on rails 
<% if current_usuario != nil %>
<%= current_usuario.email%>
<%end%>
</h1>

web_mvc/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebMvc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
<nav class="be-black white large-padding">
<ul class="no-list row center-xs middle-xs">
<li class="col-md"><%= link_to 'Principal',root_path%></li>
<li class="col-md"><%= link_to 'Lista de articulos','/articulos'%></li>
<li class="col-md"><%= link_to 'Añadir articulo','/articulos/new'%></li>
<% if usuario_signed_in? %>
	<li class="col-md">
	<%= link_to "Cerrar sesión", destroy_usuario_session_path, method: :delete%>
	</li>
<% else %>
	<li class="col-md">
	<%= link_to "Iniciar sesión", new_usuario_session_path%>
	</li>
	<li class="col-md">
	<%= link_to "Crear cuenta", new_usuario_registration_path%>
	</li>
<%end%>
</ul>
</nav>
</header>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>